2.7.4

diff --git a/trunk/findent/Makefile.in b/trunk/findent/Makefile.in
--- a/trunk/findent/Makefile.in
+++ b/trunk/findent/Makefile.in
@@ -643,6 +643,15 @@ distuninstallcheck:
 	        fi ; \
 	        $(distuninstallcheck_listfiles) ; \
 	        exit 1; } >&2
+distcleancheck: distclean
+	@if test '$(srcdir)' = . ; then \
+	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
+	  exit 1 ; \
+	fi
+	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
+	  || { echo "ERROR: files left in build directory after distclean:" ; \
+	       $(distcleancheck_listfiles) ; \
+	       exit 1; } >&2
 check-am: all-am
 check: check-recursive
 all-am: Makefile config.h
@@ -771,10 +780,6 @@ uninstall-am:
 
 maintainer-clean-local:
 	rm -rf bin share autom4te.cache
-# make distcheck complains about bison-related files
-# (not flex-related files), so disable distcleancheck:
-distcleancheck:
-	@:
 
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
